name: terraform_upgrade_myself_version

on:
  push:
    paths:
      - .github/workflows/terraform_upgrade_myself_version.yml
      - recipes/terraform_upgrade_myself_version.rb
    branches-ignore:
      - main

  schedule:
    - cron: "0 10 * * 5" # JST 19:00 (Fri)
  workflow_dispatch:

env:
  NAMESPACE: sue445
  ASSIGNEE:  sue445

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: true

      - uses: ruby/setup-ruby@afeafc3d1ab54a631816aba4c914a0081c12ff2f # v1.310.0
        with:
          ruby-version: ruby

      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version: stable

      - run: go install github.com/sue445/ghrcooldown/cmd/ghrcooldown@latest

      - name: Set envs
        run: |
          set -xe
          GH_REPO_NAME=$(echo $GITHUB_REPOSITORY | cut -d/ -f2)
          echo "GH_REPO_NAME=${GH_REPO_NAME}" >> $GITHUB_ENV

          LATEST_TERRAFORM=$(ghrcooldown latest --repo hashicorp/terraform --cooldown-days 7)
          LATEST_TERRAFORM=${LATEST_TERRAFORM#v}
          echo "LATEST_TERRAFORM=${LATEST_TERRAFORM}" >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate token
        id: generate_token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        with:
          client-id:    ${{ secrets.GH_APP_ID }}
          private-key:  ${{ secrets.GH_PRIVATE_KEY }}
          owner:        ${{ env.NAMESPACE }}
          repositories: ${{ env.GH_REPO_NAME }}

      - name: Generate arguments
        run: |
          set -xe
          if [ "${GITHUB_REF}" == "refs/heads/main" ]; then
            dry_run="false"
          else
            dry_run="true"
          fi
          echo "DRY_RUN=${dry_run}" >> $GITHUB_ENV

      - uses: sue445/sashimi_tanpopo_action@6d750aa80f9e9d16d9c7ce1bf3fd842d9bcd8d10 # v0.7.1
        with:
          recipe-files:         "${{ github.workspace }}/recipes/terraform_upgrade_myself_version.rb"
          target-dir:           "${{ github.workspace }}"
          params:               "terraform_version:${{ env.LATEST_TERRAFORM }}"
          dry-run:              "${{ env.DRY_RUN }}"
          github-repository:    "${{ env.NAMESPACE }}/${{ env.GH_REPO_NAME }}"
          message:              "Upgrade to Terraform ${{ env.LATEST_TERRAFORM }}"
          pr-title:             "Upgrade to Terraform ${{ env.LATEST_TERRAFORM }}"
          pr-body:              "ref. https://github.com/sue445/sashimi_tanpopo-personal/commit/${{ github.sha }}"
          pr-source-branch:     "terraform_${{ env.LATEST_TERRAFORM }}"
          pr-assignees:         "${{ env.ASSIGNEE }}"
          only-changes-summary: "true"
          github-token:         "${{ steps.generate_token.outputs.token }}"

      - name: Slack Notification
        uses: act10ns/slack@d96404edccc6d6467fc7f8134a420c851b1e9054 # v2.2.0
        if: always()
        continue-on-error: true
        with:
          status: ${{ job.status }}
          webhook-url: ${{ secrets.SLACK_WEBHOOK }}
