name: upgrade_go

on:
  push:
    paths:
      - .github/workflows/upgrade_go.yml
      - recipes/upgrade_go.rb

env:
  NAMESPACE: sue445
  ASSIGNEE:  sue445

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

      matrix:
        include:
          - repo: "terraform-version-updater"
            go_version: "1.25"
            golangci_lint_version: "v2.4"

          - repo: "zatsu_monitor"
            go_version: "1.25"
            golangci_lint_version: "v2.4"

          # NOTE: Dependent on https://hub.docker.com/_/golang
          - repo: "feed_squeezer"
            go_version: "1.25"
            golangci_lint_version: "v2.4"

          - repo: "gitpanda"
            go_version: "1.25"
            golangci_lint_version: "v2.4"

          - repo: "plant_erd"
            go_version: "1.25"
            golangci_lint_version: "v2.4"

          # c.f. https://cloud.google.com/appengine/docs/standard/lifecycle/support-schedule#go
          - repo: "condo3"
            go_version: "1.24.0"
            golangci_lint_version: "" # This repo doesn't use golangci-lint

    steps:
      - uses: actions/checkout@v5
        with:
          submodules: true

      - name: Generate token
        id: generate_token
        uses: actions/create-github-app-token@v2
        with:
          app-id:       ${{ secrets.GH_APP_ID }}
          private-key:  ${{ secrets.GH_PRIVATE_KEY }}
          owner:        ${{ env.NAMESPACE }}
          repositories: ${{ matrix.repo }}

      - name: checkout target repo
        uses: actions/checkout@v5
        with:
          repository: ${{ env.NAMESPACE }}/${{ matrix.repo }}
          token:      ${{ steps.generate_token.outputs.token }}
          path:       tmp/repo/

      - run: ls -la tmp/repo/

      - name: Generate arguments
        run: |
          set -xe
          if [ "${GITHUB_REF}" == "refs/heads/main" ]; then
            dry_run="false"
          else
            dry_run="true"
          fi
          echo "DRY_RUN=${dry_run}" >> $GITHUB_ENV

      - uses: sue445/sashimi_tanpopo_action@v0.3.0
        with:
          recipe-files:      "${{ github.workspace }}/recipes/upgrade_go.rb"
          target-dir:        "${{ github.workspace }}/tmp/repo"
          params:            "go_version:${{ matrix.go_version }} golangci_lint_version:${{ matrix.golangci_lint_version }} "
          dry-run:           "${{ env.DRY_RUN }}"
          git-user-name:     "sashimi_tanpopo"
          github-repository: "${{ env.NAMESPACE }}/${{ matrix.repo }}"
          message:           "Upgrade to go ${{ matrix.go_version }}"
          pr-title:          "Upgrade to go ${{ matrix.go_version }}"
          pr-source-branch:  "go_${{ matrix.go_version }}"
          pr-assignees:      "${{ env.ASSIGNEE }}"
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
